version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
    variables:
        "VERSION_MEDIUM": "25"
    exportedVariables:
        - VERSION_LOW
        - VERSION_HIGH

#variables:
# "testEnv" : "testValue1"
#exportedVariables:
#  - testEnv
 
# inputArtifacts:
# - name: hello-dev-jar
# location: hello123.class

 
steps:
- type: Command
  name: "Build hello-world"
  timeoutInSeconds: 400
  command: |
    cd amd64/hello-world
    docker build . -t helloworld1
    echo "Build Done"
  onFailure:
    - type: Command
      timeoutInSeconds: 400
      command: |
        echo "Handling Failure"
        echo "Failure successfully handled"
- type: Command
  name: "Set Variables"
  timeoutInSeconds: 30
  command: |
      export VERSION_HIGH=5
      export VERSION_LOW=13
  onFailure:
    - type: Command
      timeoutInSeconds: 400
      command: |
        echo "Handling Failure"
        echo "Failure successfully handled"

outputArtifacts:
- name: helloworld
  type: DOCKER_IMAGE
  location: helloworld1
